export const MEMOS_LIST_REQUEST = 'MEMOS_LIST_REQUEST';
export const MEMOS_LIST_SUCCESS = 'MEMOS_LIST_SUCCESS';
export const MEMOS_LIST_FAIL = 'MEMOS_LIST_FAIL';

export const MEMOS_ADD_REQUEST = 'MEMOS_ADD_REQUEST';
export const MEMOS_ADD_SUCCESS = 'MEMOS_ADD_SUCCESS';
export const MEMOS_ADD_FAIL = 'MEMOS_ADD_FAIL';

export const MEMOS_UPDATE_REQUEST = 'MEMOS_UPDATE_REQUEST';
export const MEMOS_UPDATE_SUCCESS = 'MEMOS_UPDATE_SUCCESS';
export const MEMOS_UPDATE_FAIL = 'MEMOS_UPDATE_FAIL';

export const MEMOS_DELETE_REQUEST = 'MEMOS_DELETE_REQUEST';
export const MEMOS_DELETE_SUCCESS = 'MEMOS_DELETE_SUCCESS';
export const MEMOS_DELETE_FAIL = 'MEMOS_DELETE_FAIL';
